import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { EvaluationReport } from "./EvaluationReport";
import type { AssessmentResult, Evaluation } from "../lib/adminApi";

import resultFixture from "../test/fixtures/result.json";
import pendingFixture from "../test/fixtures/evaluation.pending.json";
import runningFixture from "../test/fixtures/evaluation.running.json";
import failedFixture from "../test/fixtures/evaluation.failed.json";

/**
 * The recruiter's evaluation report, against the canonical assessment result.
 *
 * Every fixture was generated by `tools/make_report_fixtures.py` from the real
 * serialisers — `result.json` comes out of `result.build_validated`, the same
 * function the endpoint calls — so these tests run against the contract the
 * backend actually sends. Regenerating them after a contract change is what
 * makes drift show up here instead of in front of a recruiter.
 *
 * The evaluation in them came from an injected extractor, not a model. What is
 * verified is the UI and its integration with the API.
 */

const SESSION = "8c61817c76f54a36bd3df1b4199a3f9c";
const RESULT_URL = `/api/recruiter/sessions/${SESSION}/evaluation/result`;

type Stub = {
  /** 200 — a completed, self-consistent assessment. */
  result?: unknown;
  /** 409 with a status envelope — pending, running or failed. */
  statusEnvelope?: unknown;
  /** 409 with violations — the result contradicted itself. */
  violations?: string[];
  /** 404, 403, 500 … */
  status?: number;
  detail?: string;
};

function stubApi(stub: Stub) {
  const calls: string[] = [];
  const fetchMock = vi.fn(async (url: string, _init?: RequestInit) => {
    calls.push(String(url));
    if (stub.result) {
      return {
        ok: true, status: 200, json: async () => stub.result,
      } as unknown as Response;
    }
    if (stub.statusEnvelope) {
      return {
        ok: false, status: 409,
        json: async () => ({
          detail: {
            message: `The evaluation is ${
              (stub.statusEnvelope as Evaluation).status
            }; there is no result yet.`,
            evaluation: stub.statusEnvelope,
          },
        }),
      } as unknown as Response;
    }
    if (stub.violations) {
      return {
        ok: false, status: 409,
        json: async () => ({
          detail: {
            message:
              "The assessment result does not agree with itself and has not been shown.",
            violations: stub.violations,
          },
        }),
      } as unknown as Response;
    }
    const status = stub.status ?? 404;
    return {
      ok: false, status,
      json: async () => ({ detail: stub.detail ?? "nope" }),
    } as unknown as Response;
  });
  vi.stubGlobal("fetch", fetchMock);
  return { calls, fetchMock };
}

function result(patch: (r: AssessmentResult) => void = () => undefined): AssessmentResult {
  const copy = structuredClone(resultFixture) as unknown as AssessmentResult;
  patch(copy);
  return copy;
}

async function renderReport(stub: Stub) {
  const api = stubApi(stub);
  render(<EvaluationReport sessionId={SESSION} />);
  await waitFor(() => expect(screen.queryByText(/loading the evaluation/i)).toBeNull());
  return api;
}

function cardFor(skill: string): HTMLElement {
  return screen.getByRole("heading", { name: skill }).closest("article")!;
}

beforeEach(() => vi.unstubAllGlobals());
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

// --------------------------------------------------------------------------- //
//  §17 — one request, every state
// --------------------------------------------------------------------------- //
describe("loading", () => {
  it("renders the whole assessment from a single request", async () => {
    const { calls } = await renderReport({ result: result() });
    // Every figure on the page comes from one response, so the report can never
    // show halves of two different evaluations. The pilot-review panel fetches
    // its own list separately — that is a note about the assessment, not part
    // of it, and it is filtered out here rather than relaxing the rule.
    expect(calls.filter((url) => !url.endsWith("/review"))).toEqual([RESULT_URL]);
    expect(screen.getByText("Skill assessment")).toBeInTheDocument();
  });

  it("renders a completed assessment", async () => {
    await renderReport({ result: result() });
    expect(screen.getByRole("heading", { name: "Priya Sharma" })).toBeInTheDocument();
    expect(screen.getByText("Evaluated")).toBeInTheDocument();
  });

  it("renders a pending evaluation without any score", async () => {
    await renderReport({ statusEnvelope: pendingFixture });
    expect(screen.getAllByText(/evaluation queued/i).length).toBeGreaterThan(0);
    expect(screen.queryByText(/total score/i)).toBeNull();
    expect(screen.queryByText(/skill assessment/i)).toBeNull();
    expect(screen.queryByText(/interview coverage/i)).toBeNull();
  });

  it("renders a running evaluation without partial scoring", async () => {
    await renderReport({ statusEnvelope: runningFixture });
    expect(screen.getAllByText(/evaluation running/i).length).toBeGreaterThan(0);
    expect(screen.queryByText(/overall rating/i)).toBeNull();
  });

  it("renders a failure as a failed run, not as a poor candidate", async () => {
    await renderReport({ statusEnvelope: failedFixture });
    expect(screen.getByRole("heading", { name: /evaluation failed/i })).toBeInTheDocument();
    expect(
      screen.getByText(/failure of the evaluation run, not a result about the candidate/i),
    ).toBeInTheDocument();
    expect(screen.queryByText(/total score/i)).toBeNull();
  });

  it("offers a retry on failure and re-reads afterwards", async () => {
    const { fetchMock } = await renderReport({ statusEnvelope: failedFixture });
    await userEvent.click(screen.getByRole("button", { name: /run it again/i }));
    await waitFor(() =>
      expect(
        fetchMock.mock.calls.some(
          ([, init]) => (init as RequestInit | undefined)?.method === "POST",
        ),
      ).toBe(true),
    );
  });

  it("treats a missing evaluation as 'not requested yet', not as an error", async () => {
    await renderReport({ status: 404 });
    expect(screen.getByText(/no evaluation for this interview yet/i)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /run evaluation/i })).toBeInTheDocument();
  });

  it("surfaces an unauthorized session rather than an empty report", async () => {
    await renderReport({
      status: 403,
      detail: "That session does not belong to this interview.",
    });
    expect(screen.getByText(/couldn't load the evaluation/i)).toBeInTheDocument();
    expect(screen.getByText(/does not belong to this interview/i)).toBeInTheDocument();
  });

  it("surfaces a network failure the same way", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => {
      throw new TypeError("network down");
    }));
    render(<EvaluationReport sessionId={SESSION} />);
    await waitFor(() =>
      expect(screen.getByText(/can't reach the server/i)).toBeInTheDocument(),
    );
  });

  it("refuses to render a result that contradicts itself", async () => {
    await renderReport({
      violations: ["total_score 51 is not the sum of the discussed skills (38)"],
    });
    expect(screen.getByText(/was not shown/i)).toBeInTheDocument();
    expect(screen.getByText(/is not the sum of the discussed skills/)).toBeInTheDocument();
    // And no scores leak through from a half-rendered result.
    expect(screen.queryByText(/overall rating/i)).toBeNull();
  });
});

// --------------------------------------------------------------------------- //
//  Header
// --------------------------------------------------------------------------- //
describe("the header", () => {
  it("names the candidate, the interview and the version sat against", async () => {
    await renderReport({ result: result() });
    expect(screen.getByText("Senior Backend Engineer — payments screen")).toBeInTheDocument();
    expect(screen.getByText("v1")).toBeInTheDocument();
    expect(screen.getByText(/Senior Backend Engineer, Payments · Senior/)).toBeInTheDocument();
    expect(screen.getByText("Interview complete")).toBeInTheDocument();
    expect(screen.getByText(/deep_evidence_v2/)).toBeInTheDocument();
  });

  it.each([
    ["short", "Short"],
    ["medium", "Medium"],
    ["deep", "Deep"],
  ])("shows the configured interview depth %s as %s", async (value, label) => {
    await renderReport({
      result: result((r) => {
        r.interview.interview_depth = value;
      }),
    });
    const depth = screen.getByText("Interview depth").closest("div")!;
    expect(within(depth).getByText(label)).toBeInTheDocument();
  });

  it("never labels the interview depth with a probe stage", async () => {
    await renderReport({ result: result() });
    const depth = screen.getByText("Interview depth").closest("div")!;
    expect(depth.textContent).not.toMatch(/direct|probed/);
    expect(
      screen.getByText(/Separate from how far any one question was followed up/i),
    ).toBeInTheDocument();
  });
});

// --------------------------------------------------------------------------- //
//  §9 — the overall figures are read, never derived
// --------------------------------------------------------------------------- //
describe("the overall assessment", () => {
  it("shows the engine's own total, maximum, percentage and rating", async () => {
    await renderReport({ result: result() });
    const { overall } = resultFixture as unknown as AssessmentResult;
    expect(screen.getByText(String(overall.total_score))).toBeInTheDocument();
    expect(screen.getByText(`/ ${overall.max_score}`)).toBeInTheDocument();
    expect(screen.getByText(`${overall.percentage}%`)).toBeInTheDocument();
    expect(screen.getByText(overall.overall_rating)).toBeInTheDocument();
  });

  it("renders the figures the API sent even when they disagree with the rows", async () => {
    // The backend refuses a contradictory result; if one ever arrives, the
    // console must not paper over it with arithmetic of its own.
    await renderReport({
      result: result((r) => {
        r.overall.total_score = 7;
        r.overall.max_score = 90;
        r.overall.percentage = 7.8;
        r.overall.overall_rating = "Poor";
      }),
    });
    expect(screen.getByText("7")).toBeInTheDocument();
    expect(screen.getByText("/ 90")).toBeInTheDocument();
    expect(screen.getByText("7.8%")).toBeInTheDocument();
  });

  it.each([
    "Not suitable for this role",
    "Needs further evaluation",
    "Proceed to next round",
  ])("renders the recommendation %s verbatim", async (recommendation) => {
    await renderReport({
      result: result((r) => {
        r.overall.recommendation = recommendation;
      }),
    });
    expect(screen.getByText(recommendation)).toBeInTheDocument();
  });

  it("shows the explanation without adding a number to it", async () => {
    await renderReport({ result: result() });
    const explanation = (resultFixture as unknown as AssessmentResult).summary
      .recommendation_explaination;
    expect(screen.getByText(explanation)).toBeInTheDocument();
    expect(explanation).not.toMatch(/\d+\s*\/\s*\d+|\d+%/);
  });

  it("says what the score's denominator was", async () => {
    await renderReport({ result: result() });
    expect(screen.getByText(/The score covers/)).toBeInTheDocument();
    expect(
      screen.getByText(/reported as coverage above, not counted against the candidate/i),
    ).toBeInTheDocument();
  });
});

// --------------------------------------------------------------------------- //
//  Coverage — beside the score, never inside it
// --------------------------------------------------------------------------- //
describe("coverage", () => {
  it("reports how much of the assessment was reached", async () => {
    await renderReport({ result: result() });
    const { coverage } = resultFixture as unknown as AssessmentResult;
    const block = screen.getByText("Interview coverage").closest("div")!;
    expect(within(block).getByText(String(coverage.skills_discussed))).toBeInTheDocument();
    expect(
      within(block).getByText(new RegExp(`of ${coverage.skills_total} skills`)),
    ).toBeInTheDocument();
    expect(
      within(block).getByText(new RegExp(`${coverage.coverage_percentage}% assessed`)),
    ).toBeInTheDocument();
  });

  it("names the mentioned and never-asked skills as coverage, not weakness", async () => {
    await renderReport({ result: result() });
    const block = screen.getByText("Interview coverage").closest("div")!;
    expect(block.textContent).toMatch(/1 mentioned/);
    expect(block.textContent).toMatch(/1 not asked/);
  });

  it("keeps a coverage gap out of the improvement areas", async () => {
    await renderReport({ result: result() });
    const gaps = (resultFixture as unknown as AssessmentResult).skills
      .filter((s) => s.discussion_status === "not_discussed")
      .map((s) => s.skill_name);
    expect(gaps.length).toBeGreaterThan(0);
    const improvements = screen
      .getByText("Areas for improvement")
      .closest("div")!.textContent!.toLowerCase();
    for (const gap of gaps) expect(improvements).not.toContain(gap.toLowerCase());
  });
});

// --------------------------------------------------------------------------- //
//  Skills
// --------------------------------------------------------------------------- //
describe("skill assessment", () => {
  it("lists every published skill, exact name, in the API's order", async () => {
    await renderReport({ result: result() });
    const expected = (resultFixture as unknown as AssessmentResult).skills.map(
      (s) => s.skill_name,
    );
    expect(screen.getAllByRole("heading", { level: 4 }).map((h) => h.textContent)).toEqual(
      expected,
    );
  });

  it("renders all five criteria for a discussed skill, on the payload's scale", async () => {
    await renderReport({ result: result() });
    const fixture = resultFixture as unknown as AssessmentResult;
    const skill = fixture.skills.find((s) => s.discussion_status === "discussed")!;
    const card = cardFor(skill.skill_name);
    for (const criterion of fixture.scales.criteria) {
      expect(
        within(card).getByRole("img", {
          name: `${criterion}: ${skill.criteria[criterion]} out of ${fixture.scales.criterion_max}`,
        }),
      ).toBeInTheDocument();
    }
  });

  it("takes each skill's maximum from the payload, not a constant", async () => {
    await renderReport({
      result: result((r) => {
        r.skills.forEach((s) => {
          s.max_score = 30;
        });
      }),
    });
    const skill = (resultFixture as unknown as AssessmentResult).skills.find(
      (s) => s.discussion_status === "discussed",
    )!;
    const card = cardFor(skill.skill_name);
    expect(within(card).getByText("/30")).toBeInTheDocument();
    expect(within(card).queryByText("/25")).toBeNull();
  });

  it("marks a skill that does not reach the overall total", async () => {
    await renderReport({ result: result() });
    const mentioned = (resultFixture as unknown as AssessmentResult).skills.find(
      (s) => s.discussion_status === "mentioned",
    )!;
    const card = cardFor(mentioned.skill_name);
    expect(within(card).getByText("Mentioned only")).toBeInTheDocument();
    expect(within(card).getByText(/not counted in the total/i)).toBeInTheDocument();
  });

  it("shows a not-discussed skill with the contract's wording and no score", async () => {
    await renderReport({ result: result() });
    const gap = (resultFixture as unknown as AssessmentResult).skills.find(
      (s) => s.discussion_status === "not_discussed",
    )!;
    const card = cardFor(gap.skill_name);
    expect(within(card).getByText("Not discussed")).toBeInTheDocument();
    expect(within(card).getByText("Not discussed in interview")).toBeInTheDocument();
    expect(within(card).getByText(/coverage gap, not a weakness/i)).toBeInTheDocument();
    expect(within(card).queryByRole("img", { name: /out of/ })).toBeNull();
  });

  it("offers no control that edits a score, a rating or a recommendation", async () => {
    await renderReport({ result: result() });
    // The assessment itself is read-only. The only inputs on the page belong to
    // the pilot review, which records what a human thought BESIDE the result and
    // cannot write to it — so the check is scoped to everything else rather than
    // dropped.
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    const outside = (role: string) =>
      screen.queryAllByRole(role).filter((el) => !review.contains(el));
    expect(outside("textbox")).toHaveLength(0);
    expect(outside("spinbutton")).toHaveLength(0);
    expect(outside("combobox")).toHaveLength(0);
    expect(screen.queryByRole("button", { name: /override|edit|adjust/i })).toBeNull();
    // And nothing inside it is bound to a score: there is no field whose value
    // is the total, the percentage, the rating or the criteria.
    const fields = within(review).queryAllByRole("textbox");
    for (const field of fields) {
      expect((field as HTMLInputElement).value).not.toMatch(/\d+\s*\/\s*\d+/);
    }
  });
});

// --------------------------------------------------------------------------- //
//  Depth
// --------------------------------------------------------------------------- //
describe("depth reached and depth demonstrated", () => {
  async function panelFor(skill: string, reached: string, demonstrated: string) {
    await renderReport({
      result: result((r) => {
        const row = r.skills.find((s) => s.skill_name === skill)!;
        row.depth.depth_reached = reached as never;
        row.depth.depth_demonstrated = demonstrated as never;
      }),
    });
    return cardFor(skill);
  }

  const SUBJECT = "Reconciliation";

  it.each([
    ["direct", "direct", "Direct answer", "Direct answer"],
    ["direct", "deep_probed", "Direct answer", "Probed twice"],
    ["deep_probed", "direct", "Probed twice", "Direct answer"],
    ["deep_probed", "deep_probed", "Probed twice", "Probed twice"],
  ])(
    "shows %s / %s as two separate labelled values",
    async (reached, demonstrated, reachedLabel, demonstratedLabel) => {
      const card = await panelFor(SUBJECT, reached, demonstrated);
      const reachedBlock = within(card).getByText("Depth reached").closest("div")!;
      const shownBlock = within(card).getByText("Depth demonstrated").closest("div")!;
      expect(within(reachedBlock).getByText(reachedLabel)).toBeInTheDocument();
      expect(within(shownBlock).getByText(demonstratedLabel)).toBeInTheDocument();
      expect(within(card).getByText(/How far Tara investigated this skill/i)).toBeInTheDocument();
      expect(
        within(card).getByText(/How far the candidate's own evidence went/i),
      ).toBeInTheDocument();
    },
  );

  it("explains deeply probed but shallowly demonstrated without calling it low", async () => {
    const card = await panelFor(SUBJECT, "deep_probed", "direct");
    expect(
      within(card).getByText(/Tara investigated further than the evidence reached/i),
    ).toBeInTheDocument();
  });

  it("explains a directly answered but deeply demonstrated skill as saturation", async () => {
    const card = await panelFor(SUBJECT, "direct", "deep_probed");
    expect(
      within(card).getByText(/went further than the interview needed to probe/i),
    ).toBeInTheDocument();
  });

  it("keeps the fixture's own contrasting cases visible side by side", async () => {
    await renderReport({ result: result() });
    const over = cardFor("Idempotent design");
    const saturated = cardFor("Reconciliation");
    expect(within(over).getByText(/Tara investigated further/i)).toBeInTheDocument();
    expect(
      within(saturated).getByText(/went further than the interview needed/i),
    ).toBeInTheDocument();
  });
});

// --------------------------------------------------------------------------- //
//  §13 — the drill-down: question, turn, evidence, criterion
// --------------------------------------------------------------------------- //
describe("question and evidence drill-down", () => {
  it("shows what was asked, what came back, and what was taken from it", async () => {
    await renderReport({ result: result() });
    const fixture = resultFixture as unknown as AssessmentResult;
    const skill = fixture.skills.find(
      (s) => s.discussion_status === "discussed" && s.evidence_count > 0,
    )!;
    const card = cardFor(skill.skill_name);
    await userEvent.click(within(card).getByText(/Questions and evidence/));
    // Scoped to the drill-down: the skill header shows its own depth summary,
    // so the same wording legitimately appears twice on the card.
    const drilldown = within(card).getByText(/Questions and evidence/)
      .closest("details")! as HTMLElement;

    const question = fixture.questions.find((q) => q.skill_id === skill.skill_id)!;
    expect(within(drilldown).getByText(question.question_text)).toBeInTheDocument();
    for (const turn of question.turns) {
      if (turn.answer) {
        expect(within(drilldown).getByText(turn.answer)).toBeInTheDocument();
      }
    }
    const item = fixture.evidence.find((e) => e.skill_id === skill.skill_id)!;
    expect(within(drilldown).getByText(`“${item.candidate_quote}”`)).toBeInTheDocument();
    expect(
      within(drilldown).getByText(new RegExp(`Turn ${item.turn_id}`)),
    ).toBeInTheDocument();
    // More than one item can bear on the same criterion; that is the data,
    // not a duplicate render.
    expect(
      within(drilldown).getAllByText(new RegExp(`supports ${item.supports_criterion}`))
        .length,
    ).toBeGreaterThan(0);
  });

  it("shows each question's own depth pair", async () => {
    await renderReport({ result: result() });
    const fixture = resultFixture as unknown as AssessmentResult;
    const skill = fixture.skills.find((s) => s.skill_name === "Reconciliation")!;
    const card = cardFor(skill.skill_name);
    await userEvent.click(within(card).getByText(/Questions and evidence/));
    const drilldown = within(card).getByText(/Questions and evidence/)
      .closest("details")! as HTMLElement;
    // The question's own pair, not the skill header's.
    expect(
      within(drilldown).getByText(/Reached Direct · Demonstrated Deep probed/),
    ).toBeInTheDocument();
  });

  it("quotes the candidate verbatim, exactly as the API validated it", async () => {
    await renderReport({ result: result() });
    for (const item of (resultFixture as unknown as AssessmentResult).evidence) {
      expect(screen.getByText(`“${item.candidate_quote}”`)).toBeInTheDocument();
    }
  });

  it("invents nothing when a skill produced no evidence", async () => {
    await renderReport({
      result: result((r) => {
        r.evidence = [];
        r.skills.forEach((s) => {
          s.evidence_count = 0;
        });
      }),
    });
    expect(screen.queryAllByRole("blockquote" as never)).toHaveLength(0);
  });

  it("marks a turn the scanner excluded rather than hiding it", async () => {
    await renderReport({
      result: result((r) => {
        r.questions[0].turns[0].excluded = true;
        r.questions[0].turns[0].excluded_reason = "override attempt";
      }),
    });
    const skill = (resultFixture as unknown as AssessmentResult).skills.find(
      (s) => s.skill_id === (resultFixture as unknown as AssessmentResult).questions[0].skill_id,
    )!;
    const card = cardFor(skill.skill_name);
    await userEvent.click(within(card).getByText(/Questions and evidence/));
    expect(within(card).getByText(/Excluded · override attempt/)).toBeInTheDocument();
  });
});

// --------------------------------------------------------------------------- //
//  §27 — what the report never shows
// --------------------------------------------------------------------------- //
describe("what the report never shows", () => {
  it("carries no prompt, no reasoning and no extractor rationale", async () => {
    await renderReport({ result: result() });
    const text = document.body.textContent!.toLowerCase();
    for (const leak of [
      "you assess one skill", "strict json", "candidate_text_start",
      "system prompt", "chain of thought", "reasoning:",
    ]) {
      expect(text).not.toContain(leak);
    }
  });

  it("does not execute candidate-provided markup", async () => {
    await renderReport({
      result: result((r) => {
        r.evidence[0].candidate_quote = '<img src=x onerror="window.__pwned=1">';
        r.questions[0].turns[0].answer = "<script>window.__pwned = 1</script>";
      }),
    });
    expect((window as unknown as { __pwned?: number }).__pwned).toBeUndefined();
    expect(document.querySelector("script[data-injected]")).toBeNull();
    // The text is shown as text.
    expect(screen.getByText(/<img src=x onerror=/)).toBeInTheDocument();
  });
});

// --------------------------------------------------------------------------- //
//  Embedded in the review screen
// --------------------------------------------------------------------------- //
describe("embedded in the interview review screen", () => {
  it("does not repeat the candidate's name the screen already shows", async () => {
    const api = stubApi({ result: result() });
    render(<EvaluationReport sessionId={SESSION} embedded />);
    await waitFor(() => expect(screen.queryByText(/loading the evaluation/i)).toBeNull());
    expect(screen.queryByRole("heading", { name: "Priya Sharma" })).toBeNull();
    expect(screen.getByText("Senior Backend Engineer — payments screen")).toBeInTheDocument();
    expect(api.calls.filter((url) => !url.endsWith("/review"))).toHaveLength(1);
  });
});

// --------------------------------------------------------------------------- //
//  §7 — coverage must not read as performance
// --------------------------------------------------------------------------- //
describe("the coverage / performance distinction", () => {
  it("says outright that coverage is not the candidate's score", async () => {
    await renderReport({ result: result() });
    const fixture = resultFixture as unknown as AssessmentResult;
    expect(
      screen.getByText(
        /Coverage is a measure of how complete the interview was, not of how the candidate performed/i,
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText(new RegExp(`${fixture.overall.percentage}% above is their score`)),
    ).toBeInTheDocument();
  });

  it("names the skills the interview did not assess", async () => {
    await renderReport({ result: result() });
    const unassessed = (resultFixture as unknown as AssessmentResult).skills
      .filter((s) => s.discussion_status !== "discussed")
      .map((s) => s.skill_name);
    expect(unassessed.length).toBeGreaterThan(0);
    const note = screen
      .getByText(/This assessment covers/)
      .closest("p")!.textContent!;
    for (const name of unassessed) expect(note).toContain(name);
  });

  it("says nothing about completeness when everything was assessed", async () => {
    await renderReport({
      result: result((r) => {
        r.skills.forEach((s) => {
          s.discussion_status = "discussed";
          s.counts_toward_overall_score = true;
        });
        r.coverage = {
          skills_total: r.skills.length,
          skills_discussed: r.skills.length,
          skills_mentioned: 0,
          skills_not_discussed: 0,
          coverage_percentage: 100,
        };
      }),
    });
    expect(screen.queryByText(/This assessment covers/)).toBeNull();
  });

  it("never multiplies the score by coverage or shows a composite", async () => {
    await renderReport({ result: result() });
    const fixture = resultFixture as unknown as AssessmentResult;
    const composite = Math.round(
      (fixture.overall.percentage * fixture.coverage.coverage_percentage) / 100,
    );
    // Scanned element by element, not over the concatenated body: adjacent
    // nodes ("/ 50" then "66%") join into digits that were never displayed.
    const allowed = new Set([
      String(fixture.overall.percentage),
      String(fixture.coverage.coverage_percentage),
    ]);
    const shown = new Set<string>();
    for (const node of document.querySelectorAll("p, span, dd, li, h1, h2, h3, h4")) {
      const own = [...node.childNodes]
        .filter((n) => n.nodeType === Node.TEXT_NODE)
        .map((n) => n.textContent ?? "")
        .join("");
      for (const match of own.matchAll(/(\d+(?:\.\d+)?)\s*%/g)) shown.add(match[1]);
    }
    expect([...shown].filter((v) => !allowed.has(v))).toEqual([]);
    expect(shown.has(String(composite))).toBe(false);
    expect(shown).not.toContain(composite);
  });
});

// --------------------------------------------------------------------------- //
//  Pilot review — calibration data, never an override
// --------------------------------------------------------------------------- //
describe("the pilot review panel", () => {
  function stubWithReview() {
    const posted: Array<Record<string, unknown>> = [];
    const fetchMock = vi.fn(async (url: string, init?: RequestInit) => {
      const address = String(url);
      if (address.endsWith("/review") && init?.method === "POST") {
        const body = JSON.parse(String(init.body));
        posted.push(body);
        return {
          ok: true,
          status: 201,
          json: async () => ({
            ...body,
            evaluation_id: "ev_test",
            session_id: SESSION,
            ai_recommendation: "Needs further evaluation",
            ai_total_score: 33,
            ai_percentage: 66,
            ai_coverage_percentage: 50,
            pilot_run_id: "pilot_test",
            created_at: 0,
            updated_at: 0,
          }),
        } as unknown as Response;
      }
      if (address.endsWith("/review")) {
        return {
          ok: true,
          status: 200,
          json: async () => ({
            session_id: SESSION,
            evaluation_id: "ev_test",
            reviews: [],
            verdicts: ["agree", "disagree", "needs_review"],
            reasons: ["wrong_evidence", "wrong_skill"],
          }),
        } as unknown as Response;
      }
      return { ok: true, status: 200, json: async () => result() } as unknown as Response;
    });
    vi.stubGlobal("fetch", fetchMock);
    return { posted };
  }

  async function renderWithReview() {
    const api = stubWithReview();
    render(<EvaluationReport sessionId={SESSION} />);
    await waitFor(() => expect(screen.queryByText(/loading the evaluation/i)).toBeNull());
    return api;
  }

  it("says plainly that a review changes nothing about the assessment", async () => {
    await renderWithReview();
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    expect(within(review).getByText(/cannot change the score/i)).toBeInTheDocument();
  });

  it("will not record a verdict without a reviewer", async () => {
    await renderWithReview();
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    await userEvent.click(within(review).getByRole("button", { name: "Agree" }));
    expect(within(review).getByRole("button", { name: /record review/i })).toBeDisabled();
  });

  it("will not record a disagreement with no category", async () => {
    await renderWithReview();
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    await userEvent.type(within(review).getByLabelText(/reviewer name/i), "Asha");
    await userEvent.click(within(review).getByRole("button", { name: "Disagree" }));
    const record = within(review).getByRole("button", { name: /record review/i });
    expect(record).toBeDisabled();

    await userEvent.click(
      within(review).getByRole("button", { name: /score does not match/i }),
    );
    expect(record).toBeEnabled();
  });

  it("posts the verdict, the categories and the reviewer's own recommendation", async () => {
    const { posted } = await renderWithReview();
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    await userEvent.type(within(review).getByLabelText(/reviewer name/i), "Asha");
    await userEvent.click(within(review).getByRole("button", { name: "Disagree" }));
    await userEvent.click(
      within(review).getByRole("button", { name: /attributed to the wrong skill/i }),
    );
    await userEvent.selectOptions(
      within(review).getByLabelText(/what would you have recommended/i),
      "Not suitable for this role",
    );
    await userEvent.click(within(review).getByRole("button", { name: /record review/i }));

    await waitFor(() => expect(posted).toHaveLength(1));
    expect(posted[0]).toMatchObject({
      reviewer: "Asha",
      verdict: "disagree",
      reasons: ["wrong_skill"],
      recommendation: "Not suitable for this role",
    });
    // Nothing it sends could be mistaken for an edit to the assessment.
    expect(Object.keys(posted[0])).not.toContain("score");
    expect(Object.keys(posted[0])).not.toContain("criteria");
  });

  it("leaves every figure on the page exactly as it was", async () => {
    await renderWithReview();
    const fixture = resultFixture as unknown as AssessmentResult;
    // `innerText` is not implemented in jsdom; `textContent` is the equivalent
    // for a comparison that only has to notice a figure changing.
    const before = document.body.textContent ?? "";
    const review = screen.getByRole("heading", { name: "Pilot review" }).closest("section")!;
    await userEvent.type(within(review).getByLabelText(/reviewer name/i), "Asha");
    await userEvent.click(within(review).getByRole("button", { name: "Disagree" }));
    await userEvent.click(
      within(review).getByRole("button", { name: /recommendation is wrong/i }),
    );
    await userEvent.click(within(review).getByRole("button", { name: /record review/i }));
    await waitFor(() =>
      expect(within(review).getByText(/changes nothing about the assessment/i)).toBeInTheDocument(),
    );
    expect(screen.getByText(fixture.overall.recommendation)).toBeInTheDocument();
    const after = document.body.textContent ?? "";
    for (const figure of [
      String(fixture.overall.total_score),
      String(fixture.overall.percentage),
      fixture.overall.overall_rating,
      fixture.overall.recommendation,
      String(fixture.coverage.coverage_percentage),
    ]) {
      expect(after.includes(figure)).toBe(before.includes(figure));
    }
  });
});
