"""Turn the benchmark's JSON results into EVALUATOR_CALIBRATION.md.

The markdown is generated rather than written by hand for one reason: a
calibration report a person edits is a calibration report that will eventually
disagree with the run it claims to describe. Every number here comes from
`evals/results/`.

    python tools/write_calibration_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "evals" / "results"
OUT = ROOT / "EVALUATOR_CALIBRATION.md"


def rate(value) -> str:
    return "—" if value is None else f"{value * 100:.0f}%"


def main() -> int:
    from evals import benchmark as B

    det = json.loads((RESULTS / "evaluator_benchmark_deterministic.json").read_text())
    live_path = RESULTS / "evaluator_benchmark_live.json"
    if not live_path.exists():
        print("no live results yet — run `python -m evals.benchmark --live`", file=sys.stderr)
        return 1
    live = json.loads(live_path.read_text())

    cases = {c["case_id"]: c for c in B.cases()}
    totals = live["totals"]
    tele = live["telemetry"]
    lines: list[str] = []
    w = lines.append

    w("# Evaluator calibration")
    w("")
    w("Generated by `tools/write_calibration_report.py` from `evals/results/`. Every")
    w("number below comes from a run; nothing here is hand-edited.")
    w("")
    w("The question this answers is not \"does the evaluator run\" — Phase 10 settled")
    w("that — but \"are its decisions right\". It is measured against")
    w("`evals/datasets/evaluator_benchmark.json`, whose expected outcomes are authored")
    w("to be ones a human reviewer would agree with, and whose criterion expectations")
    w("are **ranges**: inside the range is calibration variance, outside it is error.")
    w("")

    # ---- headline ------------------------------------------------------- #
    w("## Headline")
    w("")
    w("```")
    w(f"cases                              {totals['total_cases']}")
    w(f"free of material error             {totals['cases_free_of_critical_failures']}"
      f"  ({rate(totals['critical_pass_rate'])})")
    w(f"fully inside every authored range  {totals['passed_cases']}"
      f"  ({rate(totals['pass_rate'])})")
    w(f"material errors                    {totals['material_errors']}")
    w(f"calibration variances              {totals['calibration_variances']}")
    w("```")
    w("")
    w("Two rates on purpose. A single pass percentage would let \"scored a skill nobody")
    w("asked about\" hide inside \"was one point low on Clarity\", and those are not the")
    w("same kind of wrong. The first number is the one that gates anything.")
    w("")

    # ---- provider ------------------------------------------------------- #
    w("## Provider")
    w("")
    w("```")
    w(f"provider              {tele['provider']}")
    w(f"configured model      {tele['configured_model']}")
    w(f"resolved model        {tele['resolved_model']}")
    w(f"silent fallback       {tele['silent_model_fallback']}")
    w(f"calls                 {tele['calls']}")
    w(f"prompt tokens         {tele['prompt_tokens']:,}")
    w(f"completion tokens     {tele['completion_tokens']:,}")
    w(f"provider latency      {tele['latency_ms_total'] / 1000:.1f}s total")
    w(f"structured modes      {', '.join(tele['structured_modes']) or '—'}")
    w(f"schema errors         {tele['schema_errors']}")
    w("```")
    w("")

    # ---- deterministic -------------------------------------------------- #
    w("## Mode A — deterministic")
    w("")
    w("The benchmark checking itself before it is allowed to judge a model: are the")
    w("gold labels consistent with the rules the engine computes in code? A wrong case")
    w("would condemn a correct evaluator.")
    w("")
    w(f"- **{det['cases_checked']} cases**, {len(det['findings'])} findings")
    rec = det["recommendation_cases"]
    w(f"- **{sum(r['passed'] for r in rec)}/{len(rec)} recommendation rules** hold, and every")
    w("  explanation is free of numbers the evaluator did not compute")
    w("")
    w("| case | expected | actual | |")
    w("|---|---|---|---|")
    for row in rec:
        w(f"| `{row['case_id']}` | {row['expected']} | {row['actual']} | "
          f"{'pass' if row['passed'] else '**FAIL**'} |")
    w("")

    # ---- agreement ------------------------------------------------------ #
    w("## Mode B — what the real model got right")
    w("")
    w("| measured | asserted by | agreed | rate |")
    w("|---|---|---|---|")
    labels = {
        "discussion_status": "Discussion status",
        "skill_attribution": "Skill attribution",
        "depth_reached": "Depth reached",
        "depth_demonstrated": "Depth demonstrated",
        "dimensions": "Evidence dimensions",
        "score_range": "Skill total in range",
        "criterion_vocabulary": "Criterion vocabulary",
        "quote_verbatim": "Quotes verbatim",
        "no_fabricated_or_protected_content": "No fabricated / protected content",
        "score_ceiling_respected": "Score ceiling respected",
    }
    for key, label in labels.items():
        row = live["agreement"].get(key)
        if row is None:
            continue
        w(f"| {label} | {row['asserted']} cases | {row['agreed']} | {rate(row['rate'])} |")
    w("")

    # ---- criteria ------------------------------------------------------- #
    w("## Per-criterion agreement")
    w("")
    w("Only cases that *focus* on a criterion are graded for it: a case built to")
    w("discriminate Accuracy has no authority over Communication.")
    w("")
    w("| criterion | graded | in range | outside | rate |")
    w("|---|---|---|---|---|")
    for criterion, row in live["criterion_accuracy"].items():
        w(f"| {criterion} | {row['graded_cases']} | {row['within_expected_range']} | "
          f"{row['outside_expected_range']} | {rate(row['rate'])} |")
    w("")

    # ---- failures ------------------------------------------------------- #
    material = [f for f in live["findings"] if f["severity"] == B.CRITICAL]
    variance = [f for f in live["findings"] if f["severity"] == B.CALIBRATION]

    w("## Failures")
    w("")
    if live["failures_by_class"]:
        w("By class: " + ", ".join(
            f"`{k}` {v}" for k, v in sorted(live["failures_by_class"].items())) + ".")
    else:
        w("None.")
    w("")

    w("### Material errors")
    w("")
    if not material:
        w("None. No case scored an undiscussed skill, attributed evidence to a skill the")
        w("question did not test, fabricated a quote, named a criterion from the dimension")
        w("list, took demonstrated depth from the probe count, or inverted a matched pair.")
    else:
        w("| case | check | expected | actual | class | why it matters |")
        w("|---|---|---|---|---|---|")
        for f in material:
            w(f"| `{f['case_id']}` | {f['check']} | `{f['expected']}` | `{f['actual']}` | "
              f"{f['failure_class']} | {f['reason']} |")
    w("")

    w("### Calibration variance")
    w("")
    if not variance:
        w("None.")
    else:
        w("A subjective judgement outside an authored range by one point, or an extractor")
        w("that missed a dimension. Recorded, not gated.")
        w("")
        w("| case | check | expected | actual | authored reason |")
        w("|---|---|---|---|---|")
        for f in variance:
            reason = cases.get(f["case_id"], {}).get("reason", "")
            w(f"| `{f['case_id']}` | {f['check']} | `{f['expected']}` | `{f['actual']}` | "
              f"{reason[:120]} |")
    w("")

    # ---- per case ------------------------------------------------------- #
    w("## Every case")
    w("")
    w("| case | group | material | in range | score | reached / demonstrated | status |")
    w("|---|---|---|---|---|---|---|")
    for cid, row in live["cases"].items():
        obs = row["observed"]
        depth = f"{obs.get('depth_reached','—')} / {obs.get('depth_demonstrated','—')}"
        w(f"| `{cid}` | {row['group']} | {'ok' if row['critical_clean'] else '**FAIL**'} | "
          f"{'ok' if row['passed'] else 'variance'} | {obs.get('score','—')} | {depth} | "
          f"{obs.get('discussion_status','—')} |")
    w("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
